version: '3.8'
services:
  video-uploader:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MAX_UPLOAD_SIZE=10737418240
      - MAX_MEMORY=33554432
      - UPLOAD_PATH=/app/uploads
      - TEMP_UPLOAD_PATH=/app/temp_uploads
    volumes:
      - uploads:/app/uploads
      - temp_uploads:/app/temp_uploads

volumes:
  uploads:
  temp_uploads: